### ISSUE TITLE
GET /sale/product-offers/{offerId}.

### ISSUE THREAD

**Issue by kamilkozak** [imper86/php-allegro-api#1]
Bardzo proszę o dodanie zasobu `GET /sale/product-offers/{offerId}` oraz powiązanego `GET /sale/product-offers/{offerId}/operations/{operationId}`

**Comment by imper86** [comment]
@kamilkozak zrobione. Sorry, że tak długo, z jakiegoś powodu miałem wyłączone powiadomienia o issues na tym repozytorium.

**Comment by kamilkozak** [comment]
@imper86 Dziękuje. Masz jakieś plany na wersję na PHP 8 ?

**Comment by imper86** [comment]
@kamilkozak zrobiona :). W związku z tym, że wraz ze zmianą wersji w composer na >=7.4 musiałem też poaktualizować inne paczki, zrobiłem wersję v2.0.0 - wystarczy zmienić wersję w composer.json, struktura libki pozostała bez zmian, więc żadne zmiany w kodzie nie będą konieczne.

**Comment by kamilkozak** [comment]
@imper86 Uszczęśliwiłeś człowieka. W końcu mogę przejść w projekcie na PHP8. Gdybyś miał możliwość sponsorowania na githubie to napewno jednym zostanę. Nie chcę już przeginać, ale w najbliższych dniach chciałem użyć też "php-baselinker-api" jest szansa, że zadziała na PHP8?

**Comment by imper86** [comment]
@kamilkozak miło mi, dzięki :)
php-baselinker-api ogarnąłem, sprawdziłem, działa, także możesz tam również użyć php8 :)
