### ISSUE TITLE
Dodanie Loggera

### ISSUE THREAD

**Issue by Hornir91** [imper86/php-allegro-api#10]
Cześć.

Ostatnio zaktualizowałem bibliotekę do V2 i mam pytanie.

W poprzedniej wersji, tworząc instancję AllegroClient oraz AllegroAuth, mogłem podpiąć swojego loggera, który zapisywał mi wychodzące requesty oraz otrzymywane response'y.

        $this->allegroAuth = new AllegroAuth($this->appCredentials, $this->logger);
        $this->allegroClient = new AllegroClient($this->appCredentials, $this->logger);

W nowej wersji nie ma już możliwości podpięcia loggera bezpośrednio przy tworzeniu instancji.

        $this->allegroApi = new AllegroApi($this->credentials);

Jak mogę podpiąć loggera w nowszej wersji? Muszę napisać własny plugin, po czym wywołać metodę addPlugin() czy jest jakaś inna opcja?

Z góry dzięki za odpowiedź.

**Comment by imper86** [comment]
Hej,

Akurat to dodawanie loggera w konstruktorze istnieje nadal, ale to inna biblioteka :) - https://github.com/imper86/allegroapi/blob/master/src/AllegroClient.php - `imper86/allegroapi` i `imper86/php-allegro-api` robią to samo, ale to dwie oddzielne biblioteki, napisane na dwa różne sposoby :)

W każdym razie, nie musisz pisać własnego pluginu, wystarczy wpiąć sobie https://github.com/php-http/logger-plugin

Ewentualnie można oczywiście napisać swój własny jeśli zależy Ci na jakiejś customizacji

**Comment by Hornir91** [comment]
Dzięki. Ostatecznie wyszło na to, że musiałem zaimplementować swój własny plugin, bo ten podesłany nie spełniał wymagań :).

**Comment by core45** [comment]
A dlaczego są 2 biblioteki, które wygladają tak jakby robiły to samo?
Czy któraś z nich jest polecana przez ciebie? Którą wybrać?

**Comment by Hornir91** [comment]
Obydwie biblioteki robią to samo, bo obie są klientami API do Allegro :). Ogólnie mówiąc allegroapi lepiej współgra z Twoją apką, jeśli korzystasz z Symfony, a php-allegro-api, gdy używasz Laravela.

**Comment by imper86** [comment]
@core45 obydwie robią to samo, ale php-allegro-api jest nowsze i w mojej opinii lepsze. Co do integracji z frameworkami to nie zgadzam się, obydwie można zaimplementować bez problemu w Symfony i w Laravelu :).

Zamykam wątek, bo problem wygląda na rozwiązany :)
