### ISSUE TITLE
Pytanie o obiekty response

### ISSUE THREAD

**Issue by squishfunk** [imper86/php-allegro-api#13]
Witam,

Jak dobrze rozumiem aktualnie response zwracany jest tylko jako string przez co trzeba go tłumaczyć na arraya (przykład poniżej) lub na własne obiekty
```php
json_decode($api->sale()->offers()->get()->getBody()->getContents(), true)
```

Czy macie w planach rozwinąć SDK o obiektowy response z endpointów?
np 
```php
foreach($api->sale()->offers()->get()->getBody()->getContents()->getOffers() as $offer){
    $offer->getId()
    ...
}
```

I jeśli nie to co stoi na przeszkodzie. Chętnie mógłbym pomóc jeśli tak :)

**Comment by imper86** [comment]
Takich planów nie ma, ale jeśli masz na tyle dużo czasu żeby to ogarnąć to czemu nie :).
Oczywiście to by nam psuło BC, ale można by to było potraktować jako nową major wersję.

Ja niestety się za to nie zabiorę, ostatnio w ogóle nie dysponuję czasem żeby cokolwiek na githubie ogarniać :)
