### ISSUE TITLE
Rozwój API do allegro nowa metoda shipment-management

### ISSUE THREAD

**Issue by Gradziu31** [imper86/php-allegro-api#15]
Witam 
na allegro pojawiła się informacja o tym, że kończą wsparcie dla /parcel-management. Teraz całość ma działać na /shipment-management. Czy macie w planach rozwinąć API o nowe metody jeśli tak to kiedy można się spodziwać nowej wersji paczki, bardzo mi zależy ;) 

proszę o odpowiedź:)

Wiadomość na allegro:
https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY

Aktualnie w naszym API wspieramy dwa podejścia dla tworzenia przesyłek w ramach usługi “Wysyłam z Allegro”:
nowe zasoby /shipment-management, za pomocą których możesz zarządzać swoimi przesyłkami, utworzyć etykietę, pobrać protokół nadania, a także zamówić podjazd kuriera,
dotychczasowe zasoby /parcel-management, które przestaliśmy już wspierać. Od 21.09.2023 są one oznaczone jako Deprecated, natomiast w czwartym kwartale 2024 roku zostaną całkowicie usunięte.

**Comment by imper86** [comment]
Nie mam tego w planach, niestety brakuje czasu. Ale możesz przygotować PR i chętnie wmerdżuję :)

**Comment by mgalej** [comment]
@imper86 Witam, wrzuciłem w PR od siebie aktualizację dla tego zasobu ;)

**Comment by imper86** [comment]
Super, dzięki za Twój wkład :) jest merge i nowa wersja, zamykam w takim razie :)
