### ISSUE TITLE
Zmiany w związku z GPSR

### ISSUE THREAD

**Issue by fzdunek** [imper86/php-allegro-api#17]
Hej, miałeś może chwilę sprawdzić zmiany w związku z GPSR?

dochodzą dwa nowe resources:
https://developer.allegro.pl/documentation#tag/Responsible-persons
https://developer.allegro.pl/documentation#tag/Responsible-producers

**Comment by fzdunek** [comment]
@imper86 przeglądałem poprzednie issues i stwierdziłem, że wystawiając PR będzie szybciej :) 
https://github.com/imper86/php-allegro-api/pull/18

**Comment by imper86** [comment]
wydane z wersją 2.4.0 :)
https://github.com/imper86/php-allegro-api/releases/tag/v2.4.0
