### ISSUE TITLE
getAuthorizationUri nie zwraca url'a z Sandboxem

### ISSUE THREAD

**Issue by gmatkowski** [imper86/php-allegro-api#2]
\Imper86\PhpAllegroApi\OauthOAuthClient.php:
linia: 84

if ($this->credentials->isSandbox()) {
    $uri->withHost($uri->getHost() . EndpointHost::SANDBOX_SUFFIX);
}
tworzona jest nowa instancja $uri przez co poprzednia NIE JEST modyfikowana i zwracany URL pozostaje ten sam.

**Comment by imper86** [comment]
@gmatkowski poprawione, dzięki
