### ISSUE TITLE
custom response classes

### ISSUE THREAD

**Issue by kamilkozak** [imper86/php-allegro-api#4]
@imper86  Ostatnio zacząłem używać php-baselinker-api i zauważyłem, że każdy zasób ma własną klasę odpowiedzi np AddCategoryResponse. Jest jakiś sprytny sposób, żeby osiągnąć coś takiego również w tej bibliotece? Innymi słowy chciałbym owinąć zwracany ResponseInterface we własny dekorator ale nie pisać odnowa metod $api->sale()->(...) itd. Jakie jest Twoje podejście?

**Comment by imper86** [comment]
@kamilkozak do php-baselinker-api napisałem po prostu klasy ręcznie, ale z dzisiejszej perspektywy uważam to za bezsens. Dla tej biblioteki planuję dodać modele tworzone za pomocą openapi generator z ich pliku swagger, ale jakoś nie mam czasu się za to zabrać. Z drugiej strony też trochę obawiam się niespójności pomiędzy tym co allegro wystawia w pliku a tym co jest na produkcji. Na ich profilu na githubie było mnóstwo zgłoszeń o błędach w ich openapi, więc kwestia jest nadal do rozważenia.
