### ISSUE TITLE
PHP Allegro i Laravel

### ISSUE THREAD

**Issue by Blaaszkovsky** [imper86/php-allegro-api#6]
Cześć, jestem trochę laikiem w pisaniu odpowiednich funkcji i autoryzacji, więc liczę na pomoc. 

Zrobiłem sobie funkcję createConnection() i za jej pomocą autoryzuje aplikacje i generuje oraz zapisuje token i zwracam na niej $api - choć tutaj nie jestem przekonany czy na pewno tak powinienem robić.

        // first, create Credentials object
         $credentials = new Credentials(
             'token',
             'token',
             'redirect,
             true
         );
         $api = new AllegroApi($credentials);

         $state = 'uri';
         header(sprintf('Location: %s', $api->oauth()->getAuthorizationUri(true, $state)));

        // dump($state);
         // verify the state and fetch token
         if ($state !== $_GET['state'] ?? null) {
             throw new Exception('CSRF?!');
         }
     
         $token = $api->oauth()->fetchTokenWithCode($_GET['code']);
     
         // create TokenRepository object
         $tokenRepository = new FileTokenRepository(
             $token->getUserId(), 
             __DIR__ . '/tokens'
         );
         $tokenRepository->save($token);
         return $api;

Później na warstawie widokowej chcę skorzystać z tego $api, aby móc ściągać odpowiednio dane. Czy mogę prosić o pomoc jak to rozgryźć, aby takie rozwiązanie otrzymać?

**Comment by imper86** [comment]
Cześć,

Z funkcji `$api->oauth()->fetchTokenWithCode($_GET['code'])` powinieneś skorzystać tylko przy pierwszym pobraniu pary access/refresh token. Potem token będzie się odświeżał automatycznie refresh_tokenem jeżeli tylko dodasz do klienta [AuthenticationPlugin](https://github.com/imper86/php-allegro-api/blob/master/src/Plugin/AuthenticationPlugin.php)
