### ISSUE TITLE
Problem z fetchTokenWithCode()

### ISSUE THREAD

**Issue by tomasz-kusy** [imper86/php-allegro-api#9]
Dzięki za dobrą robotę.

Zatrzymałem się na samym początku implementacji, tj. na metodzie fetchTokenWithCode().
Dostaję 400. Po debugu nasuwa się pytanie:
Skąd metoda [generateRequest() ](https://github.com/imper86/php-allegro-api/blob/8d88190ee9f0673882f167f7ef723bac4e76eaee/src/Oauth/OauthClient.php#L135 ) miałaby wziąć host do requesta skoro builder (w tej metodzie) nie używa metody withHost() ?

**Comment by imper86** [comment]
A z tego pluginu - https://github.com/imper86/php-allegro-api/blob/master/src/Plugin/OauthUriPlugin.php :)

Natomiast 400 wynika pewnie z tego, że kod jest nieprawidłowy, lub przeterminowany. Polecam doinstalować sobie https://github.com/php-http/logger-plugin i sprawdzić co mówią logi :)

**Comment by tomasz-kusy** [comment]
Ok, dzięki. Casem trzeba palcem pokazać... getAuthorizationUri() używa jawnie withHost() a fetchTokenWithCode() przy okazji plugina :)
A problem z 400 wyniknął z tego, że your-redirect-uri to DOKŁADNIE ten sam url co podany w Allegro (i https musi być jeżeli to nie http://localhost).
